### ISSUE TITLE
11.1.1 CSS-in-JS의 장점

### ISSUE THREAD

**Issue by hyeonseong2023** [Gwangju-Web-Study/WoowahanTS_Study#63]
📝 329p

❓ CSS와 CSS-in-JS의 차이를 코드로 비교하여 CSS-in-JS의 장점을 알려주세요!

**Comment by hyeonseong2023** [comment]
```jsx
//💡styled-components 문법
const 컴포넌트명 = styled.HTML태그`
  CSS속성: ${props => 조건에 따른 값};
`;
```

---

## 1. 동적 변경
### CSS
```css
.button {
  background: blue;
}
.button-red {
  background: red;
}
```
### CSS-in-JS
```jsx
const ButtonColor = styled.button`
  background: ${props => props.color || 'blue'};
`;

<ButtonColor color="red">빨간 버튼</ButtonColor>
<ButtonColor>파란 버튼</ButtonColor>
```

## 2. 전역 스코프 구분
### CSS
```css
/* monitoring.css */
.card {
  border: 1px solid black;
}

/* equipment.css */
/* 다른 파일에서 또 선언하면 충돌로 인해 덮어씌워지거나 사용되지 않음 */
.card {  
  border: 2px solid red;
}
```
### CSS-in-JS
```jsx
const Card1 = styled.div`
  border: 1px solid black;
`;
const Card2 = styled.div`
  border: 2px solid red;
`;

<Card1>첫번째 카드</Card1>
<Card2>두번째 카드</Card2>
```

## 3. 조건부 스타일
### CSS
```css
.button {
  display: block;
}
.button.hidden {
  display: none;
}
```
### CSS-in-JS
```jsx
const Button = styled.button`
  display: ${props => props.hidden ? 'none' : 'block'};
`;

<Button>보임</Button>
<Button hidden>숨김</Button>
```
